6a Seção: Nossos materiais
tech-pro-bem/abre pull request #11
Opened 2024-10-26 00:15 UTC by KaliniV

2024-10-29 02:29 UTC, pdrmenezes commented on src/components/materials/materials.tsx
> +import mandala from "../../../public/mandala.png";
de curiosidade, o next serve arquivos estáticos, então se quiser trocar o import da mandala e passar direto na tag de <Image/> do Next, o import fica mais simples porque pode o src dele ficaria mais curtinho, tipo

```jsx
<Image src="/mandala.png" />
```

Mas eu prefiro como fizesse, com o import no topo do arquivo, que acho que fica mais fácil de ler e refatorar quando precisa

2024-10-29 02:35 UTC, pdrmenezes commented on src/components/materials/styles.module.css
> +  border-radius: 100px;
Só senti falta do efeito de hover no botão, descobri que [no figma antigo da abre](https://www.figma.com/design/iWI5HXpKlf8JB5hRFBHd3R/ABRE---Tech-Pro-Bem?node-id=3-333&node-type=canvas&t=vxNzkwVKkKyHaPE3-0) tinha algumas interações de botões, se quiseres dar uma olhada, acho que a gente pode implementar algo parecido
<img width="206" alt="Screenshot 2024-10-28 at 23 33 33" src="https://github.com/user-attachments/assets/8625216a-1f2f-4ec9-b152-247b8e304465">

2024-10-29 02:36 UTC, pdrmenezes commented on src/components/materials/styles.module.css
> +  border: 0.06rem solid var(--color-primary-darkest);
pra borda é mais comum usar px, mesmo, então não faz mal usar 1px (:

2024-10-29 02:37 UTC, pdrmenezes commented on src/components/materials/styles.module.css
> +    flex-direction: row-reverse;
boa!

2024-10-29 02:42 UTC, pdrmenezes commented on src/components/materials/styles.module.css
> +    margin-left: 8.4rem;
Se nessa classe tás usando flex, de repente rola de usar o gap, ao invés do margin-left, mas assim também funciona (:

2024-10-29 02:55 UTC, pdrmenezes commented on public/mandala.png
aqui, mesmo que a gente vá substituir essa imagem pela que vier do contentful, eu recomendaria converter o formato dela pra .webp e já colocar no repositório com a largura máxima que ela pode ter.

Só pra dar uma ideia, toda a nossa aplicação transfere mais ou menos 3mb e só a imagem tem mais 3mb, aí pode dar uma pesadinha.

Tem esse [conversor aqui](https://squoosh.app/) bem prático que gosto bastante, que dá pra jogar a imagem, escolher o formato e usar o Resize pra escolher a lagura. Vi que a maior largura que a imagem fica no site é um pouquinho mais de 600px, se jogar no Resize do site 650px de largura e qualidade de 75%, a imagem cai de 3.2mb pra 79.1kb, é uma redução de 98%. Aí só vale fazer uns testes pra garantir que a imagem não vai ficar pixelada, também (:

2024-10-30 21:29 UTC, GiovaniBiagi requested changes

2024-10-30 21:29 UTC, GiovaniBiagi commented on src/components/materials/materials.tsx
> +"use client";
É realmente necessário esse "use client"? Pergunto porque teoricamente, não temos nenhum código que pecise de interação do usuário, então poderiamos renderizar isso do lado do servidor, ao invés do lado do cliente. O que acha @KaliniV ?

2024-10-30 21:29 UTC, GiovaniBiagi commented on src/components/materials/styles.module.css
> +  border-radius: 100px;
Só trazendo mais um ponto pra essa questão do botão:
Notei que no figma temos uma pequena sombra abaixo dele. Precisamos implementar isso.
![image](https://github.com/user-attachments/assets/99872442-0d1c-4bee-aca5-daf1efd328c7)

2024-10-31 03:12 UTC, pdrmenezes commented on src/components/materials/styles.module.css
> +@media (min-width: 75em) {
notei que ele só fica em 2 colunas a partir de 1200px, será que a gente não pode ir pra esse layout de 2 colunas um pouco antes? no globals e em alguns outros componentes a gente tá usando 40em de min-width, acho que a gente pode trocar uma ideia pra encontrar um breakpoint legal pra a maior parte do site.

O que acham  @KaliniV, @JaySant, @GiovaniBiagi e @marcelluscaio?

2024-10-31 03:14 UTC, pdrmenezes reviewed
Acho que só sobrou essa minha dúvida de um breakpoint mais geral pra a gente usar.

2024-11-04 15:59 UTC, marcelluscaio requested changes
Kalini, tá mandando muito bem! Pedi alguns pequenos ajustes. Beijos!

2024-11-04 15:59 UTC, marcelluscaio commented on public/mandala.png
Essa atenção pra performance e peso de imagens eh essencial. Mas a gente precis fazer na mão? O Next não faz isso?

2024-11-04 15:59 UTC, marcelluscaio commented on src/components/materials/styles.module.css
> +@media (min-width: 75em) {
Concordo! Ate pq a imagem ta ficando muito grande  ali por volta de 800px

2024-11-04 15:59 UTC, marcelluscaio commented on src/components/materials/materials.tsx
> +"use client";
Reforço a sugestão do Giovani!

2024-11-04 15:59 UTC, marcelluscaio commented on src/components/materials/materials.tsx
> +import mandala from "../../../public/mandala.png";
Eu não tenho certeza se passando assim ainda temos a otimização de imagem do Next. Teria que verificar. Na seção Image Optimization eles fazem com o import, então deixo aqui a dúvida com vocês

2024-11-04 15:59 UTC, marcelluscaio commented on src/components/materials/materials.tsx
> +    <section className={styles.container}>
A gente usa essa classe container?

2024-11-04 15:59 UTC, marcelluscaio commented on src/components/materials/styles.module.css
> +  padding-block: 3.5rem;
A gente precisa do padding block?

2024-11-04 15:59 UTC, marcelluscaio commented on src/components/materials/styles.module.css
> +  padding: 9.5px;
Atenção com fração de pixel

2024-11-04 15:59 UTC, marcelluscaio commented on src/components/materials/styles.module.css
> +  width: 100%;
Talvez seja legal adicionar um max-width para o button. Outro ponto: alinhar com o @pdrmenezes que também fez um button. Será que dá pra virar um componente que vai ser reutilizado por vocês dois, e talvez outras partes do site também?

2024-11-04 15:59 UTC, marcelluscaio commented on src/components/materials/styles.module.css
> +  margin-bottom: 2.5rem;
Essa margin bottom não é responsabilidade do botão. Ela está aqui para separar todo o title_text do container image. Isso faz com que o ideal seja colocar gap no content

2024-11-04 15:59 UTC, marcelluscaio commented on src/components/materials/styles.module.css
> +  border: 0.06rem solid var(--color-primary-darkest);
Concordo!

2024-11-04 15:59 UTC, marcelluscaio commented on src/components/materials/styles.module.css
> +  border-radius: 100px;
Para o lado arredondado estamso trabalhando com border-radius 100vh

2024-11-04 15:59 UTC, marcelluscaio commented on src/components/materials/styles.module.css
> +    flex-direction: row-reverse;
Queria bater uma salva de palmas pra profissional que lançou um ROW-REVERSE aqui

2024-11-04 15:59 UTC, marcelluscaio commented on src/components/materials/styles.module.css
> +  }
Esse width 50% está fazendo nossa imagem não estar alinhada à esquerda. O que acontece é que somando o width do text (37%) com o gap, com 50% da imagem, não dá 100%, então nosso flex container não está preenchido. COmo está row-reverse, o espaço em branco fica na esquerda (demorei a entender o que tava acontecendo hahahaha). 

Eu excluí esse width 50%, apaguei o width em % do title_text,e  coloquei min-width 47ch no title_text, e gostei do resultado.

2024-11-04 15:59 UTC, marcelluscaio commented on src/components/materials/styles.module.css
> +    margin-bottom: 0rem;
Com a minah sugestão anterior, de tirar o margin bottom dele, isso daqui pode sair taambém

2024-11-04 15:59 UTC, marcelluscaio commented on src/components/materials/styles.module.css
> +    width: 72.8%;
Aqui, em vez de colocar uma largura em % para o botão, você pode colocar uma largura máxima pra ele, fora d amedia query mesmo. Outra coisa: o botão é alinhado à esquerda mesmo?

2024-11-04 15:59 UTC, marcelluscaio commented on src/components/materials/styles.module.css
> +    margin-bottom: 2rem;
ISso daqui podia ser um gap

2024-11-04 15:59 UTC, marcelluscaio commented on src/components/materials/styles.module.css
> +    margin-right: 4.3rem;
Não acho que precisamos desse  margin right. Não é uma boa adicionar margem para fazer alinhamento do texto, vamos buscar fazer isso de outras formas

2024-11-04 15:59 UTC, marcelluscaio commented on src/components/materials/styles.module.css
> +    margin-left: 8.4rem;
Concordo

2024-11-12 20:50 UTC, marcelluscaio commented on src/components/materials/materials.tsx
> +            height: "auto",
Retirar sizes e style. Usar fill na imagem

2024-11-12 20:50 UTC, marcelluscaio commented on src/components/materials/styles.module.css
> +}
Usar grid aqui.
A primeira coluna vai ser definida usando a medida 1fr. A segunda vai ter 40ch. A secao ainda vai ter 104px de padding right para alinhar como no figma. ISso nod esktop. PEsquisa como fazer  a estrutura do grid no mobile (dica, voce vai usar o grid-template-columns so na media query =)

2024-11-18 16:47 UTC, marcelluscaio requested changes

2024-11-18 16:47 UTC, marcelluscaio commented on src/components/materials/styles.module.css
> +  grid-template-columns: 1;
Notei um probleminha com essa abordagem, Kalini, falha minha nao ter visto antes. Estamos tendo overflow em alguns tamanhos intermediarios.

1) Troca esse grid-template-columns 1 por 1fr, (so pq o 1 eh um valor invalido).
2) Tira o grid-columne o grid-row dos elementos filhos. Em vez disso usa order 1 e order 2 para mexer no ordenamento
3) A media query precisa passar para 75em

2024-11-18 23:40 UTC, marcelluscaio requested changes
Kalini, agora ta quase la, pedi dois ajustes pequenos. Valeu por fazer os ajustes rapido! Beijos

2024-11-18 23:40 UTC, marcelluscaio commented on src/components/materials/styles.module.css
> +    padding-right: 104px;
Esse padding right fixo ta um pouco grande em tamanhos de tela intermediarios. Pode substituir por uma medida relativa? Usei 5.45vw e gostei

2024-11-18 23:40 UTC, marcelluscaio commented on src/components/materials/styles.module.css
> +    gap: 134px;
mesma coisa aqui, pode trocar esse gap por 7vw?

2024-11-19 10:35 UTC, marcelluscaio approved these changes

2024-11-21 03:54 UTC, GiovaniBiagi commented on tsconfig.json
> +      "@/*": ["./src/*", "./public/*"]
porque adicionamos esse public aqui? 🤔

2024-11-21 04:20 UTC, GiovaniBiagi approved these changes
Vou deixar aprovado, depois vemos essa questão de adicionar o diretório public no tsconfig

2024-11-27 22:21 UTC, merged