1a Seção: Componente Hero
tech-pro-bem/abre pull request #16
Opened 2024-10-31 05:07 UTC by JaySant

2024-11-04 19:52 UTC, marcelluscaio requested changes
Muito bom trabalho, Jay! Fiz alguns pedidos nos comentários

2024-11-04 19:52 UTC, marcelluscaio commented on src/app/layout.tsx
> +        <Hero />
O hero entendo que vai na página, nao no layout

2024-11-04 19:52 UTC, marcelluscaio commented on src/app/components/hero/hero.module.css
> +  }
Esse height quebra o layout. Sugiro usar um padding-block baseado em dvh

2024-11-11 21:27 UTC, JaySant commented on src/app/layout.tsx
> +        <Hero />
@marcelluscaio Feito as mudanças, no commit: [e1b4f2b](https://github.com/tech-pro-bem/abre/pull/16/commits/e1b4f2b075e0f06d4141e869fa58c3ac4acd38df)

2024-11-11 21:29 UTC, JaySant commented on src/app/components/hero/hero.module.css
> +  }
@marcelluscaio Feito as mudanças, no commit: [e3d4eac](https://github.com/tech-pro-bem/abre/pull/16/commits/e3d4eacf77ca88acbc27782d64a72bde36c1914f)

2024-11-11 22:27 UTC, pdrmenezes commented
Único comentário é que antes de fechar o PR tem uns conflitos de código que precisam ser resolvidos. Te aconselharia a dar um pull (merge ou rebase) da main e atualizar o PR (@marcelluscaio acho que prefere rebase e @GiovaniBiagi acho que prefere merge hahah mas ambas resolvem o problema)

2024-11-11 23:49 UTC, marcelluscaio commented on src/app/components/hero/hero.module.css
> +  }
Boa!

2024-11-11 23:52 UTC, marcelluscaio commented on src/app/page.tsx
> +    </div>
O hero ja tem uma section dentro dele, pode tirar essa div, Jay

2024-11-11 23:52 UTC, marcelluscaio commented on src/app/layout.tsx
> +        <Hero />
Fiz um comentario ali que voce pode tirar a div que ta por fora do Hero, pq ele ja tem uma section dentro dele segurando tudo

2024-11-11 23:53 UTC, marcelluscaio commented
Olha @JaySant , eu ADOREI esse modelo de comentar linkando um commit. Facilita demais o processo de review.

2024-11-12 00:05 UTC, marcelluscaio requested changes
Ficou excelente, Jay! Fiz tres comentarios, quando implementar me avisa

2024-11-12 00:05 UTC, marcelluscaio commented on src/app/components/hero/hero.module.css
> +  padding: 3.5rem 1.5rem 5rem;
o padding horizontal eh melhor que seja em px. Em telas pequenas isso pode fazer diferenca, ainda mais porque o h1 tem fonte grande, o texto vai quebrar

2024-11-12 00:05 UTC, marcelluscaio commented on src/app/components/hero/hero.module.css
> +  background-color: #ddf8f7;
Seria legal se essa cor estivesse vindo do nosso tema

2024-11-12 00:05 UTC, marcelluscaio commented on src/app/components/hero/hero.module.css
> +  z-index: 0;
Acho que a gente nao rpecisa desse zindex0 aqui

2024-11-15 17:44 UTC, JaySant commented on src/app/components/hero/hero.module.css
> +  background-color: #ddf8f7;
Acho que não é necessário por enquanto porque a cor do background do site vai ser colocado por ultimo, porque ele pega dois componentes que seria um degradee, nesse caso apenas foi colocado pois os icons são brancos então é provisório
![image](https://github.com/user-attachments/assets/8c57a808-3166-4a9b-9d67-45bbf5f8193e)

2024-11-18 14:22 UTC, marcelluscaio commented on src/app/components/hero/hero.module.css
> +  background-color: #ddf8f7;
Legal. Adiciona um comentário no código então?

2024-11-18 15:41 UTC, JaySant commented on src/app/components/hero/hero.module.css
> +  background-color: #ddf8f7;
beleza

2024-11-18 16:07 UTC, JaySant commented on src/app/page.tsx
> +    </div>
@marcelluscaio mudança feita no commit:[c708be4](https://github.com/tech-pro-bem/abre/pull/16/commits/c708be4729f916b6bbafb2e5d23b1c20bbf761ec)

2024-11-18 16:32 UTC, JaySant commented on src/app/components/hero/hero.module.css
> +  padding: 3.5rem 1.5rem 5rem;
@marcelluscaio mudanças realizadas no commit: [7db8911](https://github.com/tech-pro-bem/abre/pull/16/commits/7db8911754faecb98a777d183984cf1cd86b04c6)

2024-11-18 16:32 UTC, JaySant commented on src/app/components/hero/hero.module.css
> +  z-index: 0;
@marcelluscaio mudanças realizadas no commit: [7db8911](https://github.com/tech-pro-bem/abre/pull/16/commits/7db8911754faecb98a777d183984cf1cd86b04c6)

2024-11-18 16:33 UTC, JaySant commented on src/app/components/hero/hero.module.css
> +  background-color: #ddf8f7;
@marcelluscaio adicionei o comentario no commit: [7db8911](https://github.com/tech-pro-bem/abre/pull/16/commits/7db8911754faecb98a777d183984cf1cd86b04c6)

2024-11-19 10:50 UTC, marcelluscaio approved these changes

2024-11-20 00:18 UTC, GiovaniBiagi commented on src/app/page.tsx
> +      <Hero />;
Retirar easter egg

2024-11-20 00:19 UTC, GiovaniBiagi commented on src/app/components/hero/icons/icon-right.tsx
> +export const RightIcon = (props: SVGProps<SVGSVGElement>) => {
Já que o @pdrmenezes moveu todos os icones para a pasta /components/icons, seria ideal colocar este lá também.

2024-11-20 00:20 UTC, GiovaniBiagi approved these changes
Alterar somente os pontos que comentei e por mim está pronto pra merge! 👊🏼

2024-11-20 15:46 UTC, JaySant commented on src/app/components/hero/icons/icon-right.tsx
> +export const RightIcon = (props: SVGProps<SVGSVGElement>) => {
@GiovaniBiagi alterado a mudança está no commit [428e497](https://github.com/tech-pro-bem/abre/pull/16/commits/428e4971dc05828842fbc2ec34f42b84a44d3d54)

2024-11-20 15:46 UTC, JaySant commented on src/app/page.tsx
> +      <Hero />;
Retirado está no commit [428e497](https://github.com/tech-pro-bem/abre/pull/16/commits/428e4971dc05828842fbc2ec34f42b84a44d3d54)

2024-11-20 15:49 UTC, merged