7a seção: Perguntas frequentes
tech-pro-bem/abre pull request #21
Opened 2024-11-10 00:45 UTC by KaliniV

2024-11-12 19:45 UTC, marcelluscaio requested changes
Excelente, Kalini! Gosteo demais como o código veio bem redondinho!

2024-11-12 19:45 UTC, marcelluscaio commented on src/components/faq/arrow_icon.tsx
> +import * as React from "react";
Não podemos importar só as SVGPRops? Importar a lib toda aqui pode auemtnar o tamanho do bundle

2024-11-12 19:45 UTC, marcelluscaio commented on src/components/faq/faq.tsx
> +        <h1 className={styles.questions_title}>Perguntas sobre esquizofrenia</h1>
Aqui é um h2. A gente só pode ter um h1 por página

2024-11-12 19:45 UTC, marcelluscaio commented on src/components/faq/faq.tsx
> +            </details>
Achei muito chique o uso do details e do summary aqui, tá de super parabéns =D

2024-11-12 19:45 UTC, marcelluscaio commented on src/components/faq/styles.module.css
> +  line-height: var(--line-height-1);
Adorei que voce lembrou de botar line-height, mas parece que a variavel nao esta definida.

2024-11-12 19:45 UTC, marcelluscaio commented on src/app/styles/theme.css
Precisa descomentar as line heights

2024-11-12 19:45 UTC, marcelluscaio commented on src/components/faq/styles.module.css
> +  background-color: #ffffff;
Cor precisa vir do tema

2024-11-12 19:45 UTC, marcelluscaio commented on src/components/faq/styles.module.css
> +    transform: rotate(180deg);
<3

2024-11-12 19:45 UTC, marcelluscaio commented on src/components/faq/styles.module.css
> +  min-height: 3.5em;
Acho que nao precisamos trabalhar com min-height. Quem vai definir isso é o tamanho do conteúdo + padding do pai

2024-11-12 19:45 UTC, marcelluscaio commented on src/components/faq/styles.module.css
> +  padding: 0px 24px;
Acho melhor definir esse padding no elemento pai. Define padding-inline usando px, e define padding-block usando rem (.25rem)

2024-11-12 19:45 UTC, marcelluscaio commented on src/components/faq/styles.module.css
> +  cursor: pointer;
O cursor pointer eh melhor no details

2024-11-12 19:45 UTC, marcelluscaio commented on src/components/faq/styles.module.css
> +  transition: 0.2s;
Especifica a transition de que, por questoes de performance.

2024-11-12 19:45 UTC, marcelluscaio commented on src/components/faq/styles.module.css
> +}
Bela implementação aqui!

2024-11-12 19:45 UTC, marcelluscaio commented on src/components/faq/styles.module.css
> +  }
Nao precisamos colocar margem pra cima e pra baixo. Acho que pode tirar totalmente esse margin-block daqui

2024-11-12 19:45 UTC, marcelluscaio commented on src/components/faq/styles.module.css
> +    font-size: var(--font-size-5);
Essa fonte varia diferente da nossa variacao padrao de fonte?

2024-11-12 19:45 UTC, marcelluscaio commented on src/components/faq/vector.tsx
> +import * as React from "react";
Mesma questao desse import feito no outro componente

2024-11-14 13:38 UTC, KaliniV commented on src/components/faq/faq.tsx
> +            </details>
Ui Ui kkk obrigada!!

2024-11-14 14:08 UTC, KaliniV commented on src/components/faq/styles.module.css
> +  min-height: 3.5em;
o padding do pai (.faq_list) não define altura do summary, o que ele mexe são nas laterias desse componente.

2024-11-14 14:09 UTC, KaliniV commented on src/components/faq/styles.module.css
> +  min-height: 3.5em;
eu tirando  o min height esse texto fica comprimido

2024-11-14 14:10 UTC, KaliniV commented on src/components/faq/styles.module.css
> +  min-height: 3.5em;
![Captura de tela de 2024-11-14 11-10-12](https://github.com/user-attachments/assets/99eb0144-8cfa-475b-8990-925ae61b4946)

2024-11-14 14:33 UTC, KaliniV commented on src/components/faq/arrow_icon.tsx
> +import * as React from "react";
atualizado commit: [6864a5e](https://github.com/tech-pro-bem/abre/pull/21/commits/6864a5e967817a36141cfe5202c7aba41807ccff)

2024-11-14 18:02 UTC, KaliniV commented on src/components/faq/styles.module.css
> +  line-height: var(--line-height-1);
atualizado commit: [0af470b](https://github.com/tech-pro-bem/abre/pull/21/commits/0af470b62fcf5868f76630c49cf959a274ec635c)

2024-11-14 18:04 UTC, KaliniV commented on src/components/faq/styles.module.css
> +  background-color: #ffffff;
commit: [0af470b](https://github.com/tech-pro-bem/abre/pull/21/commits/0af470b62fcf5868f76630c49cf959a274ec635c)

2024-11-14 18:10 UTC, KaliniV commented on src/components/faq/styles.module.css
> +  min-height: 3.5em;
como conversamos pelo slack, sera mantido, mas utilizando rem. atualizado commit: https://github.com/tech-pro-bem/abre/pull/21/commits/cef8fd5106e47255f290495549a8776fdbba3309

2024-11-14 18:11 UTC, KaliniV commented on src/components/faq/styles.module.css
> +  padding: 0px 24px;
Atualizado commit: https://github.com/tech-pro-bem/abre/pull/21/commits/9763f592d15efcdb8f1628baf77e364e1e6b2378

2024-11-14 18:36 UTC, KaliniV commented on src/components/faq/styles.module.css
> +    font-size: var(--font-size-5);
Sim, pois a fonte se mantem do mesmo tamanho em ambos(desktop e mobile) 16px,  ela não varia que nem as outras que seguem o theme.

2024-11-14 18:40 UTC, KaliniV commented on src/components/faq/styles.module.css
> +  cursor: pointer;
Opa, alteração realizada no commit: https://github.com/tech-pro-bem/abre/pull/21/commits/d406f87674c1fa7ac425216a6d234807903402cf

2024-11-14 18:42 UTC, KaliniV commented on src/components/faq/styles.module.css
> +  transition: 0.2s;
Especificado no commit: https://github.com/tech-pro-bem/abre/pull/21/commits/a41c2920b68508bac367318b3dc041461e43fc09

2024-11-14 18:42 UTC, KaliniV commented on src/components/faq/styles.module.css
> +  }
removido commit: https://github.com/tech-pro-bem/abre/pull/21/commits/a41c2920b68508bac367318b3dc041461e43fc09

2024-11-18 23:49 UTC, marcelluscaio approved these changes
Excelente trabalho, @KaliniV !

2024-11-19 00:50 UTC, GiovaniBiagi approved these changes
Parabéns pela implementação @KaliniV ! Código limpo, semântico e fácil de entender 👏🏼

2024-11-19 10:40 UTC, merged