10a seção:  Footer
tech-pro-bem/abre pull request #24
Opened 2024-11-21 18:31 UTC by KaliniV

2024-12-06 14:13 UTC, pdrmenezes commented on src/components/footer/footer.tsx
> +        <Image
Como essa logo entra em vigor a partir de 1390px (que é bem largo), ela fica bem grande. Talvez valha colocar uma largura máxima pra essa imagem ou pensar em mudar o layout perto do padrão que a gente definiu de 40em

<img width="1947" alt="Screenshot 2024-12-06 at 11 07 47" src="https://github.com/user-attachments/assets/f715b6e1-962f-466c-a03a-a03170ecc36c">

2024-12-06 14:14 UTC, pdrmenezes commented on src/components/about/about.tsx
> +    <section
boa! já criasse os ids pra linkar a página!

2024-12-06 14:16 UTC, pdrmenezes commented on src/components/footer/footer.tsx
> +          <NavBar />
Coisa pequena que não interfere em nada: eu não chamaria de navbar, pode até ser 'nav', mas não é 'bar' tipo as que a gente tem em header ou na lateral, sabe? Acho que seria só uma nav, mas não precisa trocar 😂

2024-12-06 14:20 UTC, pdrmenezes commented on src/components/footer/navbar/styles.module.css
> +}
se os estilos são os mesmos não faz sentido criar a classe `content_container` e usar nos dois lugares?

2024-12-06 14:21 UTC, pdrmenezes commented on src/components/footer/navbar/styles.module.css
> +    display: flex;
se o `display: flex` já tá declarado na classe base ali em cima não precisa repetir ele aqui, já que não muda pra outro display

2024-12-06 14:28 UTC, pdrmenezes commented on src/components/footer/styles.module.css
> +  aspect-ratio: 123/123;
vale lembrar que o aspect-ratio é uma fração, então, `123 / 123` é a mesma coisa que a versão simplificada `1 / 1`, que fica mais evidente que é um aspect-ratio quadrado

2024-12-06 15:52 UTC, pdrmenezes commented on src/components/footer/styles.module.css
> +  position: relative;
acho que não precisa desse position relative aqui, se tirar a prop "fill" da imagem e passar uma largura e altura (que são quadrados), a imagem não precisa ter essa prop que põe na imagem um  `position: absolute`

2024-12-06 15:56 UTC, pdrmenezes commented on src/components/footer/styles.module.css
> +    margin-right: 8.75rem;
como tás usando uma grid e esse content_text é uma das células do grid tu tás mudando a estrutura do grid, que acaba criando uma sobreposição de uma célula na outra, talvez trabalhar com padding ou com a largura do próprio grid seja melhor

<img width="1115" alt="Screenshot 2024-12-06 at 12 50 56" src="https://github.com/user-attachments/assets/7d74ed13-0c59-4a15-a678-9e2ee43c7b1a">

2024-12-06 15:56 UTC, pdrmenezes commented on src/components/footer/styles.module.css
> +  width: 96%;
precisa mesmo desse 96% aqui?

2024-12-06 16:00 UTC, pdrmenezes commented on src/components/footer/styles.module.css
> +  padding-left: 20px;
normalmente o padding serve pra dar respiro da borda do container, é incomum ter padding de um só lado em designs majoritariamente simétricos que é o nosso caso, se tivesse que adicionar padding de um lado mas não do outro, talvez valha pensar o porquê

2024-12-06 16:03 UTC, pdrmenezes commented on src/components/footer/styles.module.css
> +    margin-right: 2.188rem;
tás trabalhando com margens no grid mas o grid também tem gap, que normalmente é melhor de trabalhar que margem. rola de usar  o `column-gap`, por exemplo, pra distanciar as colunas, ao invés de margens.

2024-12-06 16:05 UTC, pdrmenezes commented on src/components/footer/styles.module.css
> +    margin-right: 8.75rem;
aí aqui, se tirar o `width: 53%` e as margens, ficas com menos número mágico e a ideia do design se mantém, de repente dá pra trabalhar com gap entre colunas diferente entre as colunas 1-2, 2-3 e 3-4

<img width="1403" alt="Screenshot 2024-12-06 at 13 04 14" src="https://github.com/user-attachments/assets/32ba9d21-74c1-4f84-b56a-a40cb70c756f">

2024-12-06 16:11 UTC, pdrmenezes requested changes
Boa! Levantei alguns pontos mas nem todos **precisam** ser implementados, são só sugestões e outros perguntas, mesmo

Uma coisa que acho legal de pensar quando tô criando interfaces é: no design o pessoal não passou breakpoints intermediários entre mobile e desktop mas se eu tivesse que criar um layout que fosse se transformando aos poucos entre mobile e desktop, como ele seria?

Um exemplo pro rodapé: à medida que a tela fica menor, as colunas do rodapé vão empilhando (ex: de 4 passa pra 2 colunas, que passa pra 1) e aí sim tu trocaria a ordem dos elementos como o pessoal de design fez.

Mas isso é mais um ponto de debate que solicitação de alteração (:

2024-12-09 22:27 UTC, marcelluscaio reviewed
Comecando o code review,d esculpa a demora

2024-12-09 22:27 UTC, marcelluscaio commented on src/components/faq/styles.module.css
> +  margin-block: 80px;
Retirar margin da secao

2024-12-09 22:27 UTC, marcelluscaio commented on src/components/footer/navbar/navbar.tsx
> +        <div className={styles.content_container}>
Podemos tirar essa div daqui. Os filhos de uma ul devems er sempre lis

2024-12-09 22:27 UTC, marcelluscaio commented on src/components/footer/navbar/navbar.tsx
> +        <div className={styles.content_container}>
Podemos tirar div daqui

2024-12-09 22:27 UTC, marcelluscaio commented on src/components/footer/navbar/styles.module.css
> +  gap: 4.5rem;
Esse gap aqui me preocupa um pouco. 
Qual o resultado que queremos? duas colunas?

2024-12-09 22:27 UTC, marcelluscaio commented on src/components/footer/navbar/styles.module.css
> +}
Se tirarmos a div isso daqui vai sumir

2024-12-09 23:11 UTC, marcelluscaio requested changes
Bom trabalho, @KaliniV ! Temos alguns ajustes ai pra fazer

2024-12-09 23:11 UTC, marcelluscaio commented on src/components/footer/styles.module.css
> +  grid-template-columns: 123px 20ch;
Dois valores absolutos aqui pode gerar overflow. Sugiro fazer auto 1fr, e ver se podemos ter overflow no nosso breakpoint minimo

2024-12-09 23:11 UTC, marcelluscaio commented on src/components/footer/styles.module.css
> +  margin-bottom: 2.19rem;
Retirar margin

2024-12-09 23:11 UTC, marcelluscaio commented on src/components/footer/styles.module.css
> +  flex-direction: column;
Legal o uso aqui. Dica pro futuro: se algo nao vai usar flex-direction:row voce pode economizar uma linha de codigo e aplicar display grid e gap

2024-12-09 23:11 UTC, marcelluscaio commented on src/components/footer/styles.module.css
> +.content_navbar {
retirar margin

2024-12-09 23:11 UTC, marcelluscaio commented on src/components/footer/styles.module.css
> +  margin-bottom: 2rem;
retirar margin

2024-12-09 23:11 UTC, marcelluscaio commented on src/components/footer/styles.module.css
> +    grid-template: "logo_icon navbar text_content donation";
Vamos precisar tratar o footer nas larguras intermediarias tambem. Entre 450px e 1440 px ta um pouco quebrado

2024-12-09 23:11 UTC, marcelluscaio commented on src/components/footer/styles.module.css
> +    margin-right: 2.188rem;
Retirar margin

2024-12-09 23:11 UTC, marcelluscaio commented on src/components/footer/styles.module.css
> +    margin-bottom: 3rem;
Retirar margin

2024-12-09 23:11 UTC, marcelluscaio commented on src/components/footer/styles.module.css
> +    margin-right: 8.75rem;
Concordo, essa margem ta gerando esse overflow ali

2024-12-12 03:24 UTC, marcelluscaio commented on src/components/footer/styles.module.css
> +  padding-left: 20px;
Hahaha vamo ver isso!

2024-12-19 21:42 UTC, pdrmenezes approved these changes

2025-01-08 22:47 UTC, GiovaniBiagi commented
@KaliniV , precisamos voltar com o texto sublinhado no link de LGPD.

2025-01-13 00:52 UTC, GiovaniBiagi approved these changes
@KaliniV , deixei dois comentários sobre a estilização que gostaria que você verificasse. Tirando isso, o trabalho ficou muito bom, parabéns!
Vou deixar aprovado e assim que você fizer essas correções e validar que elas estão de acordo com o design, coloca um print aqui nos comentários do PR e pode mergear!

2025-01-13 00:52 UTC, GiovaniBiagi commented on src/components/footer/styles.module.css
> +  .donation_title_text {
Tem alguma coisa rolando nessa classe aqui, que o gap não está sendo aplicado corretamente, consegue verificar por favor?
![image](https://github.com/user-attachments/assets/87bd67bc-8ad8-42e1-99f4-b985f10115a6)

2025-01-13 19:47 UTC, JaySant approved these changes

2025-01-15 20:14 UTC, KaliniV commented on src/components/footer/styles.module.css
> +  .donation_title_text {
ele esta sendo aplicado entre o titulo e o texto. diminuindo a fonte como foi pontuado acima, deu para utilizar o gap conforme esta no prototipo de 1rem

2025-01-15 20:24 UTC, KaliniV commented on src/components/footer/styles.module.css
> +  .donation_title_text {
commit: [9502eb0](https://github.com/tech-pro-bem/abre/pull/24/commits/9502eb0057db3a5a958a4863ab79cbf9ae80d54e)

2025-01-15 20:24 UTC, KaliniV commented on src/components/footer/styles.module.css
> +  font-size: var(--font-size-5);
commit: [9502eb0](https://github.com/tech-pro-bem/abre/pull/24/commits/9502eb0057db3a5a958a4863ab79cbf9ae80d54e)

2025-01-15 21:06 UTC, GiovaniBiagi approved these changes

2025-01-15 21:08 UTC, merged