1a Seção: Componente Header
tech-pro-bem/abre pull request #6
Opened 2024-10-09 03:01 UTC by JaySant

2024-10-09 17:26 UTC, pdrmenezes commented on src/app/header/style.css
> +  padding-right: 24px;
aqui rola de trocar `padding-left: 24px; padding-right:24px;` por `padding-inline: 1.5rem;`, por exemplo.

2024-10-09 17:27 UTC, pdrmenezes commented on src/app/header/style.css
> +  line-height: 21px;
`line-height` acho que também rola de ser 1.25rem;

2024-10-09 17:28 UTC, pdrmenezes commented on src/app/header/style.css
> +  border-radius: 100px;
uma estratégia que gosto muito de usar quando o botão é todo arredondado é usar `border-radius: 50px;` que aí mesmo que o botão mude de tamanho, a borda continua toda arredondada

2024-10-09 17:28 UTC, pdrmenezes commented on src/app/header/style.css
> +  height: 40px;
a gente precisa fixar o tamanho desse botão? será que não rola de chegar nessas medidas usando `padding`?

2024-10-09 17:29 UTC, pdrmenezes commented on src/app/header/style.css
> +  gap: 16px;
acho que como gap e padding são múltiplos de 16, rola de trocar os valores por rem, também

2024-10-09 17:30 UTC, pdrmenezes commented on src/app/header/style.css
> +  min-width: 360px;
acho que também rola de usar `em` no `min-width`

2024-10-09 17:30 UTC, pdrmenezes commented on src/app/header/style.css
> +  min-width: 360px;
também pode virar `22.5em`

2024-10-09 17:31 UTC, pdrmenezes commented on src/app/header/style.css
> +  padding-bottom: 8px;
aqui acho que também rola de usar `padding-block` com rem, que 8px também é múltiplo fácil de 16

2024-10-09 17:32 UTC, pdrmenezes commented on src/app/header/style.css
> +    height: 70px;
a gente precisa dessa altura fixa aqui?

2024-10-09 17:32 UTC, pdrmenezes commented on src/app/header/style.css
> +    padding-right: 136px;
por que a gente precisa do padding-right na logo desktop?

2024-10-09 17:33 UTC, pdrmenezes commented on src/app/header/style.css
> +    padding-left: 26px;
acho que aqui também dá pra usar rem

2024-10-09 17:34 UTC, pdrmenezes commented on src/app/header/style.css
> +    border-radius: 100px;
aqui a mesma coisa do `border-radius: 50%;`

2024-10-09 17:34 UTC, pdrmenezes commented on src/app/header/style.css
> +    height: 40px;
a gente precisa de altura e largura fixos nesse botão?

2024-10-09 17:35 UTC, pdrmenezes commented on src/app/header/style.css
> +    gap: 8px;
esses valores em px acho que rola de converter pra rem, pelo menos o do gap

2024-10-09 17:38 UTC, pdrmenezes commented on src/app/header/header.tsx
> +import "../styles/theme.css";
acho que a gente pode importar o `theme.css` no arquivo de layout, pra ele ficar disponível em todos os componentes, o que achas?

2024-10-09 17:39 UTC, JaySant commented on src/app/header/header.tsx
> +import "../styles/theme.css";
Super concordo!!

2024-10-09 17:54 UTC, JaySant commented on src/app/header/style.css
> +    padding-bottom: 8px;
Apliquei a diferença aqui pra compensar o border no hover, acha que seria uma solução melhor pra esse problema?

2024-10-09 18:13 UTC, marcelluscaio commented on src/app/header/style.css
> +    padding-bottom: 8px;
Otimo ponto, Jay. Tem outra solucao, sim. Se nao pintar a solucao nas proximas horas eu falo aqui ate o fim do dia

2024-10-09 18:16 UTC, JaySant commented on src/app/header/style.css
> +    padding-right: 136px;
Usei ele pra dar o espaçamento da logo e o navbar

2024-10-09 18:23 UTC, JaySant commented on src/app/header/style.css
> +  padding-right: 24px;
Acho uma boa

2024-10-09 18:33 UTC, pdrmenezes commented on src/app/header/header.tsx
> +    <>
Acho que aqui não precisa do fragmento já que a tag `<header>` já envolve todo o conteúdo

2024-10-09 18:35 UTC, pdrmenezes commented on src/app/header/style.css
> +  padding: 18px 24px 12px 24px;
Só de curiosidade, dá pra usar shorthand declarando só 3 valores, que equivale a "top, left-right, bottom". -> `padding: 18px 24px 12px;`

Mas eu confesso que prefiro com os quatro valores, acho que fica mais óbvio.

2024-10-09 18:43 UTC, JaySant commented on src/app/header/style.css
> +  border-radius: 100px;
Poh achei isso bem massa

2024-10-09 19:20 UTC, JaySant commented on src/app/header/style.css
> +  height: 40px;
Deu certo 0/

2024-10-09 19:29 UTC, JaySant commented on src/app/header/style.css
> +    padding-bottom: 8px;
Achei uma solução que seria colocar um border solid transparent de 1px o que acham?

2024-10-09 21:05 UTC, marcelluscaio commented on src/app/header/style.css
> +    padding-bottom: 8px;
Excelente. Dai no hover voce so troca o border color

2024-10-10 00:57 UTC, marcelluscaio reviewed
Fiz alguns comentários, depois retomo a revisão, Jay. Mas temos alguns pontos para serem trabalhados. Muito bom o que foi feito, parabéns =)

2024-10-10 00:57 UTC, marcelluscaio commented on src/app/header/header.tsx
> +        </div>
Não sei se vai ser tranquilo fazer, mas tenta não duplicar a div toda. Tenta só duplicar o botao

2024-10-10 00:57 UTC, marcelluscaio commented on src/app/header/header.tsx
> +        </nav>
Acho que seria mais interessante que os links fizessem parte de uma ul e li. Veja isso daqui

https://www.w3.org/WAI/tutorials/menus/structure/

2024-10-10 00:57 UTC, marcelluscaio commented on src/app/header/style.css
> +    border-radius: 100px;
Falamos disso na mentoria. Sugiro usar 100vh no lugar

2024-10-10 00:57 UTC, marcelluscaio commented on src/app/header/style.css
> +}
Precisamos disso?

2024-10-10 00:57 UTC, marcelluscaio commented on src/app/header/style.css
> +  min-width: 360px;
Esse min width gera overflow. Vamos pensar assim: o que acontece se tivermos um dispositivo com largura de 340px?

2024-10-10 00:57 UTC, marcelluscaio commented on src/app/header/style.css
> +  min-width: 360px;
Sugiro tirar como mencionado acima

2024-10-10 00:57 UTC, marcelluscaio commented on src/app/header/style.css
> +  margin: 0 auto;
Quando quiser centralizar, sugiro usar somente margin-inline auto. Aqui no caso estamos colocando margin-block 0 sem necessidade

2024-10-10 00:57 UTC, marcelluscaio commented on src/app/header/style.css
> +  font-weight: var(--fw-regular);
Otimo uso das variaveis do tema

2024-10-10 00:57 UTC, marcelluscaio commented on src/app/header/style.css
> +  text-underline-offset: 12px;
Aqui eh um bom caso de uso para em em vez de px

2024-10-10 00:57 UTC, marcelluscaio commented on src/app/header/style.css
> +    padding-right: 136px;
Jay, seria interessante usarmos outras estrategias para espacamento. O padding aumenta a area do elemento,e ele eh usado em casos em que estamos adicionando respiro para um elemento. Proponho a seguinte estrategia para pensar esse tipo de coisa: e se esse elemento tivesse uma borda, como seria?
PAra espacamento eu sugiro margin ou  gap

2024-10-11 18:13 UTC, pdrmenezes commented on src/app/header/style.css
> +  border-radius: 100px;
Só pra fazer uma correção da sugestão, esse border-radius: 50% só é bom se quiser fazer círculos perfeitamente redondos. não pra tua ideia do botão, foi mal

2024-10-15 20:59 UTC, marcelluscaio requested changes
Jay, a estrutura está ficando cada vez melhor. Adicionei comentários e fiz algumas perguntas. 
Algumas coisas que são mais gerais:
1) Você não está usando css modules
2) Você está declarando classes que não são usadas. Revisar e excluir todas as classes que não te uma função

2024-10-15 20:59 UTC, marcelluscaio commented on src/app/header/header.tsx
> +        <button className="button-header_mobile">Acessar materiais</button>
O que esse botao faz?

2024-10-15 20:59 UTC, marcelluscaio commented on src/app/header/header.tsx
> +      </nav>
Me incomoda um pouco a duplicação de código. Diria para extrair a nav para um componente próprio

2024-10-15 20:59 UTC, marcelluscaio commented on src/app/header/header.tsx
> +    <header className="container-header">
Jay, o header está com bastante duplicação de código. Sugiro uma estrutura mais ou menos assim:

<header>
<logo>
<acessar materiais mobile>
<navegacao>
<acessar materiais desktop>
<redes sociais>
</header>

Claro que vao ter umas divs ai no meio para organizar o conteudo, mas dessa maneira voce so vai duplicar o botao de acessar materiais. 

Outra coisa: o botao tem textos diferentes no mobile e desktop mesmo?

2024-10-15 20:59 UTC, marcelluscaio commented on src/app/header/style.css
> +  padding: 1.125rem 1.5rem 0.75rem;
eu concordo com o padding-block. Já o padding-inline pode ser um problema. Conversa com Pedro e Kalini sobre estratégias de alinhamento e vejam qual vao seguir. 
Aqui voce tem duas saídas tá?

Ou estabelece o padding-inline (mas isso deve estar numa variável pra ser usado por vários outros elementos. POssivelmente vai ser extraído pra um componente próprio), ou usa width, max-width e margin-inline auto. Eu prefiro essa última abordagem

2024-10-15 20:59 UTC, marcelluscaio commented on src/app/header/style.css
> +  gap: 1rem;
Gostei muito do uso do gap aqui, mesmo com o space-between. Isso é algo que é muito comum esqueceremos. O gap vai funcionar como uma ultima loinha de defesa quando o espaço acabar @pdrmenezes @KaliniV

2024-10-15 20:59 UTC, marcelluscaio commented on src/app/header/style.css
> +}
Ainda na lógica de última linha de defesa, semrpe gosto de adicionar um flex-wrap para garantir que não vai ter overflow em telas menores. Sugiro ainda testar esse coportamento com tamanho de fonte de 32px no seu navegador. Acho que o botão ta crescendo e a logo tá sumindo. É importante checar com a equipe de design o tamanho mínimo da logo @pdrmenezes @KaliniV  marcando rpa vocês pra vocês levarem isso em consideração também

2024-10-15 20:59 UTC, marcelluscaio commented on src/app/header/header.tsx
> +        <div className="logo_mobile">
Criamos essa classe mas não usamos ela.

2024-10-15 20:59 UTC, marcelluscaio commented on src/app/header/style.css
> +  white-space: nowrap;
Essa foi uma escolha da equipe de design?

2024-10-15 20:59 UTC, marcelluscaio commented on src/app/header/style.css
> +  padding: 0.6rem 1.25rem;
valores quebrados de padding. É bom evitar isso. Qual era o valor alvo aqui? OUtra coisa: em elementos com tamanho de fonte definida, você pode usar em, para o padding ficar vinculado ao tamanho de fonte do elemento

2024-10-15 20:59 UTC, marcelluscaio commented on src/app/header/style.css
> +}
Sugiro adicionar uma transition para o background color

2024-10-15 20:59 UTC, marcelluscaio commented on src/app/header/style.css
> +
Sugiro adicionar estilização para o estado de foco do botao. Ver com equipe de design qual o estado de foco (quando apertamos tab). Você vai aplicar isso usando :focus-visible @pdrmenezes @KaliniV atencao pra isso tambem pessoal

2024-10-15 20:59 UTC, marcelluscaio commented on src/app/header/style.css
> +  border-top: 1px solid var(--color-primary-lightest);
Sugiro aplicar essa border no container navbar mobile. Ele é o elemento mais externo

2024-10-15 20:59 UTC, marcelluscaio commented on src/app/header/style.css
> +  box-shadow: 0px 4px 4px rgba(0, 122, 255, 0.15);
Sugiro aplicar a box shadow no header

2024-10-15 20:59 UTC, marcelluscaio commented on src/app/header/style.css
> +  padding-inline: 1.5rem;
Ver comentário sobre alinhamento feito ali em cima

2024-10-15 20:59 UTC, marcelluscaio commented on src/app/header/style.css
> +  padding-block: 0.5rem;
Sugiro que o padding seja aplicado na tag a. Como ele é inline, você provavelmente vai precisar mudar para display block. O que acontece aqui: o envelope do a está maior do que ele, então no hover parece que é clicável, mas na verdade não é. Sugiro faze ro seguinte experimento: muda o padding para 5rem, coloca background-color red no li, e background-color blue no a (link), e veja a diferenca entre a area aparente, e a area de clique de fato. O li deve ser apenas um wrapper, e toda a estilização (tamanho, padding, border etc) deve estar no a

2024-10-15 20:59 UTC, marcelluscaio commented on src/app/header/style.css
> +@media (min-width: 1260px) {
usar media query com em

2024-10-15 20:59 UTC, marcelluscaio commented on src/app/header/style.css
> +    box-shadow: 0px 4px 4px rgba(0, 122, 255, 0.15);
sugiro aplicar box shadow no header

2024-10-15 20:59 UTC, marcelluscaio commented on src/app/header/style.css
> +    padding-block: 1rem;
precisamos de alguma estrategia de alinhamento nele. Ver comentario acima

2024-10-15 20:59 UTC, marcelluscaio commented on src/app/header/style.css
> +    margin-inline: 1.625em 8.5em;
Por que estamos aplicando margem na logo?

2024-10-15 20:59 UTC, marcelluscaio commented on src/app/header/style.css
> +    padding-block: 0.5rem;
mesmo comentário que fiz acima sobre padding no li x a

2024-10-15 20:59 UTC, marcelluscaio commented on src/app/header/style.css
> +    padding: 0.7rem 1.25rem;
Parte da estilização do button no desktop e mobile é a mesma. O que for igual, extrair para uma classe compartilhada. @pdrmenezes @KaliniV

2024-10-15 20:59 UTC, marcelluscaio commented on src/app/header/style.css
> +    padding: 0.7rem 1.25rem;
Sobre padding e valores em rem: evitar valores quebrados (qual era o valor desejado aqui?) e usa em vinculando à fonte do elemento sempre que possível

2024-10-15 20:59 UTC, marcelluscaio commented on src/app/header/style.css
> +    justify-content: space-around;
O space around não faz efeito aqui porque não temos espaço de sobra

2024-10-15 20:59 UTC, marcelluscaio commented on src/app/header/style.css
> +    padding-inline: 20px 30px;
Estamos usando padding para fazer espaçamento entre elementos

2024-10-15 20:59 UTC, marcelluscaio commented on src/app/header/header.tsx
> +        <div className="icons-header_desktop">
Isso deve ser uma ul, com lis que tem a

2024-10-15 20:59 UTC, marcelluscaio commented on src/app/header/style.css
> +    margin-right: 1.625rem;
O icons está com a responsabilidade de fazer o alinhamento do header todo. Acho legal tirar essa responsabilidade (margin right) daqui

2024-10-15 20:59 UTC, marcelluscaio commented on src/app/header/style.css
> +    align-items: center;
Somente o align items center não está garantindo que as imagens estejam centralizadas

2024-10-22 17:06 UTC, GiovaniBiagi commented
@JaySant , estava dando uma olhada no código, e pensei que talvez a gente pudesse melhorar um pouco a estrutura. Pensei em algo como:
- /header/components/nav -> Estilização de desktop e mobile vai junto
- /header/components/logo -> Estilização de desktop e mobile vai junto
- /header/index -> Agrupa tudo e estiliza somente o Header em si

Isso traria mais independência aos componentes e facilitaria futuras refatorações. O que você acha? E vocês @pdrmenezes @marcelluscaio o que acham?

2024-11-04 19:39 UTC, marcelluscaio submitted a review, later dismissed
O código está melhor organizado, muito bom Jay. Fiz algumas sugestões e pedidos.

2024-11-06 22:32 UTC, GiovaniBiagi commented on src/app/header/header.tsx
> +        </nav>
@marcelluscaio desconsidera esse comentário, estamos vendo durante a mentoria.

Caio, fiz as correões, estão neste commit: [709da65](https://github.com/tech-pro-bem/abre/pull/6/commits/709da6588375f4125ea645e8ce5489bd668a8214)

2024-11-27 22:37 UTC, GiovaniBiagi approved these changes

2024-12-05 20:22 UTC, pdrmenezes approved these changes
Deixei 2 comentários mas não impedem o merge

2024-12-05 20:22 UTC, pdrmenezes commented on src/components/header/styles.module.css
>  @media (min-width: 1024px) {
acho que aqui só faltou trocar pra `40em` que foi o que a gente definiu de padrão

2024-12-05 20:22 UTC, pdrmenezes commented on src/components/icons/acolhimento.tsx
Alguma razão pra ter trocado os ícones todos de `function` pra `const`?

2024-12-05 20:31 UTC, pdrmenezes commented on src/components/header/navbar/index.tsx
> +    href: "/",
Acho que já rola de linkar com as seções, né? Agora que já rolou merge com a main

2024-12-10 16:37 UTC, merged