Feat/converse com a gente
tech-pro-bem/abre pull request #9
Opened 2024-10-23 16:00 UTC by pdrmenezes

2024-10-30 21:02 UTC, GiovaniBiagi requested changes
Só um pequeno comentário a respeito da estrutura do Ícones. Do restante, ficou muito o bom o trabalho, parabéns @pdrmenezes !

2024-10-31 02:59 UTC, pdrmenezes commented on src/components/icons/index.tsx
>  import type { IconSvgProps } from "@/types";
Tinha pensado em economizar esse import no topo que precisaria importar pra todos mas acredito que separados fique muito mais fácil de dar manutenção no futuro, especialmente como conversamos quando vier o v2, concordo!

2024-11-04 15:02 UTC, marcelluscaio commented on src/components/contact-section/styles.module.css
> +}
Eu diria que o botao pode virar um componente. Ele deve apontar praos nossos tamanhos de fonte do nosso tema, mas no caso do botao em vez de deixar o tema cuidar da mudanca de fonte dependendo do tamanho da tela, nos vamos precisar mudar com media query, ja que os botos nao seguem a  logica da tipografia do resto do site

2024-11-04 15:33 UTC, marcelluscaio commented on src/components/contact-section/styles.module.css
> +    outline-offset: 4px;
Esqueci de falar antes: adorando que j´´a tá vindo tudo com hover e focus-visible. Eu só adicionaria uma transição (algo na casa de 0.3s) para ficar perfeito =)

2024-11-05 03:08 UTC, pdrmenezes commented on src/components/contact-section/index.tsx
> +          </a>
Queria bater esse papo presencialmente hehe mas um pouco da minha opinião (que não impede de reescrever o código de forma alguma, mas queria saber como vês):

Geralmente eu concordo que essa interação possa ser confusa e que a gente pode estilizar a tag "a", mas do ponto de vista do ux moderno, atualmente os botões têm vários papéis, inclusive de redirecionar pra fora do site, especialmente quando sinalizados de alguma forma como um ícone de seta a 45º, requerendo o uso de uma tag "a".

Ainda que estilizar a tag "a" seja um possibilidade, pensando no [botão reutilizável que criaremos para o site](https://github.com/tech-pro-bem/abre/blob/2bf40452947060b96f413b740e13eada6f108aea/src/components/button/button.tsx), acho que eventualmente encontraremos essa situação de que o botão vai servir pra redirecionar pra fora do site. Podemos criar um outro componente, por exemplo, chamado <LinkButton/>, que só troca a tag interna.

Também podemos seguir por aquele caminho do as='a', por exemplo, mas talvez adicione complexidade desnecessária ao código, o que achas?

2024-11-05 03:13 UTC, pdrmenezes commented on src/components/contact-section/styles.module.css
> +  filter: drop-shadow(0 20px 13px rgb(0 0 0 / 0.03)) drop-shadow(0 8px 5px rgb(0 0 0 / 0.08));
também achei curioso, no design aplicaram no grupo dos botões. Inclusive usei o drop shadow no lugar do box-shadow pra suavizar o efeito da sombra na caixa. 

Acho que não temos perda de usar em um ou outro, mas EU sou mais habituado a usar sombra nos botões, não no container deles hehe

2024-11-05 03:14 UTC, pdrmenezes commented on src/components/contact-section/styles.module.css
> +    outline-offset: 4px;
Que coincidência boa, que já adicionei a transição no outro PR que acabei de abrir sem ler esse comentário 😄

2024-11-05 03:16 UTC, pdrmenezes commented on src/components/contact-section/styles.module.css
> +}
criei uma POC no [outro PR](https://github.com/tech-pro-bem/abre/blob/2bf40452947060b96f413b740e13eada6f108aea/src/components/button/button.tsx) pra a gente ir trabalhando nele, foi só um primeiro teste

2024-11-05 10:56 UTC, marcelluscaio commented on src/components/contact-section/styles.module.css
> +  filter: drop-shadow(0 20px 13px rgb(0 0 0 / 0.03)) drop-shadow(0 8px 5px rgb(0 0 0 / 0.08));
Bora levar essa questao pra equipe de design? So pra ter certezaque nao foi por engano

2024-11-05 11:07 UTC, marcelluscaio commented on src/components/contact-section/index.tsx
> +          </a>
Eh, existe essa disussao da galera de UX se links deveriam parecer botões ou não, e eu to contigo: um link pode sim parecer um botão, isso já está culturalmente incorporado.

Minha preocupação aqui é posterior a isso: posto que nossa equipe de design já decidiu que esses links terão cara de botão, como implementar isso no html?

E aqui é o ponto, na especificação do HTML não deve haver um elemento interativo como um botão dentro de uma tag <a>. Isso pode ficar confuso para um leitor de tela por exemplo. Com isso acho que devemos sim tirar o button de dentro do <a>.

O que algumas pessoas fariam seria tirar a tag <a> e usar só um botão, mas com isso a gente estaria indo contra o funcinamento padrão da web, e dependendo de JS para navegação. 

Acho uma boa - como você fez - se basear nos padrões da web. 

Agor a aquestão do COMO fazer isso. Construir dois componentes, um <a> e um <button> com a mesma cara, é algo interessante pra se pensar. 

Eu acho que eu criaria os dois componentes, e deixaria a estilização que vai ser compartilhada no arquivo global, num css module. em a estratégia do 'as' também.

Eu já escrevi um artigo sobre isso, e não sei se ainda concordo com a visão que tinha naquele momento, em que tava bem mais cru em TS, mas vou compartilhar contigo

https://dev.to/marcelluscaio/dynamic-components-is-it-worth-it-28m5

2024-11-05 11:11 UTC, marcelluscaio commented on src/components/contact-section/styles.module.css
> +    outline-offset: 4px;
Muita sintonia!

2024-11-05 11:13 UTC, marcelluscaio commented
Cara, tudo ótimo. Só fica pendente o ajuste do button dentro da ancora (podemos falar disso numa chamada) e queria te pedir pra mudar o all d atransition pra especificar o que vamos transicionar.

Segue um artigo sobre  animações, e o trecho específico sobre isso

"
Selecting all properties
transition-property takes a special value: all. When all is specified, any CSS property that changes will be transitioned.

It can be tempting to use this value, as it saves us a good chunk of typing if we're animating multiple properties, but I recommend not using it.

As your product evolves, you (or someone on your team) will likely wind up updating this code at some point in the future. An unexpected animation could slip through.

Animation is like salt: too much of it spoils the dish. It pays to be really precise with the properties we animate."

https://www.joshwcomeau.com/animation/css-transitions/

2024-11-11 22:30 UTC, pdrmenezes commented
> Só um pequeno comentário a respeito da estrutura do Ícones. Do restante, ficou muito o bom o trabalho, parabéns @pdrmenezes !

Resolvido nesse [commit](https://github.com/tech-pro-bem/abre/pull/9/commits/5d258369397c9b7af3ca52ba9dd063a3e075b62b), @GiovaniBiagi

2024-11-11 22:31 UTC, pdrmenezes commented on src/components/contact-section/styles.module.css
> +  color: var(--color-neutral-lightest);
Resolvido nesse [commit](https://github.com/tech-pro-bem/abre/pull/9/commits/6ba269556d8d0b2a554e35b625c6a934c4dfcbd8), @marcelluscaio

2024-11-11 22:33 UTC, pdrmenezes commented on src/components/contact-section/styles.module.css
> +  filter: drop-shadow(0 20px 13px rgb(0 0 0 / 0.03)) drop-shadow(0 8px 5px rgb(0 0 0 / 0.08));
Conversado e resolvido nesse [commit](https://github.com/tech-pro-bem/abre/pull/9/commits/6782db5b84d58c796ac7a5cbb80045f0c033d92e) atualizando pro componente certo, @marcelluscaio

2024-11-11 22:40 UTC, pdrmenezes commented on src/components/contact-section/index.tsx
> +          </a>
Achei o artigo excelente como os outros teus que li! Muito didático!

Já tive que fazer isso em React e é um pouquito mais complexo que isso pra passar todas as props do React (que são diferentes das do html) pra cada componente baseado na tag, acho que de _ergonomia_ é bem interessante a solução de um componente que pode ser composto por tags diferentes ou receber aquela prop asChild que ele vira só um wrapper pro que tiver dentro (que também gera o contra de ficar mais verboso já que o componente não é auto-contido) mas a gente acaba passando um tempo maior desenvolvendo esse componente polimórfico.

Como a gente tá recendo alguns lembretes do fim do prazo, atualmente acho que a solução mais simples pra fecharmos esse PR é criar os componente button e link-button (ou algum outro nome). O que achas?

2024-11-11 22:46 UTC, pdrmenezes commented
> Cara, tudo ótimo. Só fica pendente o ajuste do button dentro da ancora (podemos falar disso numa chamada) e queria te pedir pra mudar o all d atransition pra especificar o que vamos transicionar.
> 
> Segue um artigo sobre animações, e o trecho específico sobre isso
> 
> " Selecting all properties transition-property takes a special value: all. When all is specified, any CSS property that changes will be transitioned.
> 
> It can be tempting to use this value, as it saves us a good chunk of typing if we're animating multiple properties, but I recommend not using it.
> 
> As your product evolves, you (or someone on your team) will likely wind up updating this code at some point in the future. An unexpected animation could slip through.
> 
> Animation is like salt: too much of it spoils the dish. It pays to be really precise with the properties we animate."
> 
> https://www.joshwcomeau.com/animation/css-transitions/

Excelente ponto, @marcelluscaio, inclusive no outro PR que abri levei exatamente isso em conta e criei o transition pra propriedades específicas, nessa foi só a tentação de escrever rápido, mesmo. 🤭  Resolvido nesse [commit](https://github.com/tech-pro-bem/abre/pull/9/commits/fbb1c05259091c35aaeb407b9e35c5d1acde696e)

2024-11-12 01:37 UTC, marcelluscaio commented on src/components/contact-section/index.tsx
> +          </a>
Isso! Vi que ficou truncado pq comi umas letras ali, mas eu acho que esse eh o melhor caminho mesmo:
"Eu acho que eu criaria os dois componentes, e deixaria a estilização que vai ser compartilhada no arquivo global, num css module." nessa parte aqui.

Valeu pelo elogio ao artigo <3

2024-11-12 02:14 UTC, pdrmenezes commented on src/components/contact-section/index.tsx
> +          </a>
Ops, eu não tinha pescado isso haha mas resolvi [no outro PR](https://github.com/tech-pro-bem/abre/pull/20/commits/b1c0da5c8e72e0c59324876e9e995512d6a947b7)!

2024-11-12 18:44 UTC, marcelluscaio commented on src/components/contact-section/styles.module.css
> +  color: var(--color-neutral-lightest);
A ideia era que fosse na section junto com background-color, mas o efeito eh o mesmo (ja que so temos um wrapper) pode seguir assim

2024-11-12 18:45 UTC, marcelluscaio commented on src/components/contact-section/styles.module.css
> +  filter: drop-shadow(0 20px 13px rgb(0 0 0 / 0.03)) drop-shadow(0 8px 5px rgb(0 0 0 / 0.08));
Ah que otimo que eles toparam deixar so no botao mesmo =)

2024-11-12 18:50 UTC, marcelluscaio reviewed
Pedro, por mim ta tudo certo, falta so resolver a questao do link/button! Otimo trabalho =D

2024-11-12 18:50 UTC, marcelluscaio commented on src/components/contact-section/index.tsx
> +          </a>
Depois que o outro for mergeado a gente atualizar essa parte entao?

2024-11-12 23:24 UTC, pdrmenezes commented on src/components/contact-section/styles.module.css
> +  color: var(--color-neutral-lightest);
verdade, mas achei por bem deixar como a sugestão original, [aqui](https://github.com/tech-pro-bem/abre/pull/9/commits/42cace8e18f04c98f7b33ace7a1730bc2c23cd65)

2024-11-12 23:24 UTC, pdrmenezes commented on src/components/contact-section/index.tsx
> +          </a>
Por mim, sim! Posso inclusive abrir uma issue pra isso, o que achas?

2024-11-18 23:32 UTC, marcelluscaio commented
Esse daqui precisa so ser alterado (para resolve isso https://github.com/tech-pro-bem/abre/pull/9#discussion_r1827875256 ) depois que https://github.com/tech-pro-bem/abre/pull/20 for mergeado

2024-11-19 04:27 UTC, pdrmenezes commented on src/components/contact-section/index.tsx
> +          </a>
Atualizado, enfim! [329c450](https://github.com/tech-pro-bem/abre/pull/9/commits/329c4508bc3fa1c65d2469d3b0fbb292a8c2df4b)

2024-11-19 10:17 UTC, marcelluscaio commented on src/components/contact-section/index.tsx
> +          </a>
Fico otimo

2024-11-19 10:20 UTC, marcelluscaio approved these changes
Tudo certo aqui!

2024-11-19 12:51 UTC, GiovaniBiagi approved these changes

2024-11-19 12:52 UTC, GiovaniBiagi commented
@pdrmenezes , resolvendo os conflitos, por mim tá pronto pra merge

2024-11-19 23:01 UTC, merged